"""Add ScrapperStatus and PublisherStatus models

Revision ID: g8h9i0j1k2l3
Revises: fddf832a8a36
Create Date: 2025-01-27 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g8h9i0j1k2l3'
down_revision: Union[str, Sequence[str], None] = 'fddf832a8a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create scrapper_status table
    op.create_table('scrapper_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('should_run', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrapper_status_id'), 'scrapper_status', ['id'], unique=False)
    
    # Create publisher_status table
    op.create_table('publisher_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('should_run', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publisher_status_id'), 'publisher_status', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_status_id'), table_name='publisher_status')
    op.drop_table('publisher_status')
    op.drop_index(op.f('ix_scrapper_status_id'), table_name='scrapper_status')
    op.drop_table('scrapper_status')
    # ### end Alembic commands ###